services:
  postgres:
    container_name: short_links_db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    networks:
      - links

  redis:
    image: bitnami/redis:8.0.2
    container_name: short_links_redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - links
    volumes:
      - redis_data:/bitnami/redis/data

  short_links_api:
    build: .
    container_name: short_links
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/short_links
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    ports:
      - 3333:3333
    depends_on:
      - postgres
      - redis
    networks:
      - links
    command:
      [
        "./wait-for-it.sh",
        "postgres:5432",
        "--",
        "./wait-for-it.sh",
        "redis:6379",
        "--",
        "pnpm",
        "start",
      ]

networks:
  links:
    driver: bridge

volumes:
  pg_data:
  redis_data:
